I haven't done, but fixed db
rubfan/je3-project pull request #17
Opened 2018-11-15 18:52 UTC by DemianSH

2018-11-15 20:19 UTC, DemianSH commented
Громоздко но в одном connection

2018-11-20 13:24 UTC, rubfan requested changes

2018-11-20 13:24 UTC, rubfan commented on src/main/java/ua/od/game/model/cardEntity/CardEntity.java
> +    private Integer groupId;
а зачем тут groupId ? он должен быть в своем ентити

2018-11-20 13:40 UTC, DemianSH commented on src/main/java/ua/od/game/model/cardEntity/CardEntity.java
> +    private Integer groupId;
Я через groupId связываю объекты CardEntity и CardGroupEntity

2018-11-21 19:19 UTC, rubfan requested changes
please fix notes

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/model/cardEntity/CardEntity.java
> +    private Integer groupId;
у тебя же есть id в обьекте класса CardGroupEntity

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/model/cardEntity/CardProductEntity.java
> +package ua.od.game.model.cardEntity;
у тебя пакет не является ентити это раз
два то что нейм конвеншен пакетов не совсем кемел посмотри как даются наименования в стандартных пакетах джава апи

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/model/cardEntity/CardProductEntity.java
> +package ua.od.game.model.cardEntity;
и переименуй на просто `card`

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +            " SELECT c.id card_id, c.name card_name, cp.card_group_id `group_id`, c.description card_desc\n" +
в запросах совсем не нужно использовать \n - это нужно больше тебе для чтения 
поудаляй эти символы и проверь чтобы везде были пробелы
так как у тебя перенесены конкатенации строк сами по себе

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +                setGroupId(resl.getInt("group_id"));
это проперти не нужно

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private void addGroupObj(List<CardEntity> cards, List<CardGroupEntity> groupSet) {
не нужно использовать постфикс Obj лучше переименуй на matchGroupToCards

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private void addGroupObj(List<CardEntity> cards, List<CardGroupEntity> groupSet) {
ну и в других местах тоже

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private Integer curentId = 1; //Variable is using in the methods setProductResources for correct fill Map
плохой подход в любом програмировании хранить в полях промжуточное состояние 
посторайся обойти это - тебе это не нужно

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private Map<Integer, Float> necessaryMap;
все эти поля не нужны у тебя для этого есть энтити их и используй не делай лишенй работы

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +            player1Map.put(resl.getInt("player1_id"), resl.getFloat("player1_number"));
убери внешние поля -- тут код не читается у тебя будут ошибки в многопоточном выполнениии

2018-11-21 19:19 UTC, rubfan commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +            player1Map.put(resl.getInt("player1_id"), resl.getFloat("player1_number"));
не очевидное значение в player1Map ну и в других похожих местах

2018-11-22 23:03 UTC, DemianSH commented on src/main/java/ua/od/game/model/cardEntity/CardProductEntity.java
> +package ua.od.game.model.cardEntity;
done

2018-11-22 23:03 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +            " SELECT c.id card_id, c.name card_name, cp.card_group_id `group_id`, c.description card_desc\n" +
done

2018-11-22 23:04 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +                setGroupId(resl.getInt("group_id"));
done

2018-11-22 23:04 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private void addGroupObj(List<CardEntity> cards, List<CardGroupEntity> groupSet) {
done

2018-11-22 23:04 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private Integer curentId = 1; //Variable is using in the methods setProductResources for correct fill Map
done

2018-11-22 23:04 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +    private Map<Integer, Float> necessaryMap;
done

2018-11-22 23:04 UTC, DemianSH commented on src/main/java/ua/od/game/repository/dao/impl/CardDaoImpl.java
> +            player1Map.put(resl.getInt("player1_id"), resl.getFloat("player1_number"));
done

2018-12-16 19:50 UTC, rubfan approved these changes

2018-12-16 19:51 UTC, merged